name: make-example
base: core22
version: '0.1'
summary: An example snap for a Makefile project
description: |
  Shows how to create a snap for an application that uses a Makefile for
  build and installation.

grade: devel
confinement: strict

apps:
  make-example:
    command: bin/make-example

parts:
  make-example:
    plugin: make
    source: .
